POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@acme.com",
    "password": "test",
    "roles": ["admin"]
}
// primeiro faça o signup para criar o usuário,
//depois use o mesmo email e senha para fazer o signin e obter o token JWT.

### signin
POST http://localhost:3001/auth/signin
Content-Type: application/json

{
    "email": "test@acme.com",
    "password": "test"
}

### forgot password
POST http://localhost:3001/auth/forgot-password
Content-Type: application/json

{
    "email": "test@acme.com"
}

### reset password
POST http://localhost:3001/auth/reset-password
Content-Type: application/json

{
    "token": "COLE_O_RESET_TOKEN_AQUI",
    "newPassword": "new-password"
}
